smtp_host: pro3.mail.ovh.net
smtp_port: 587
imap_host: pro3.mail.ovh.net
imap_port: 993
username: mailing@artscroises.be
SENDER: mailing@artscroises.be
sendername: Arts Croisés asbl
db: data/Subscribers.csv
MAX_ADDR_PER_MAIL: 100
MAX_MAILS_PER_HOUR: 2000
PAUSE: 10
SENT_FOLDER: mailing

