artscroises:
  MAILCONFIG: 'artscroisesmailing'
  database: data/Subscribers.csv
  SHEETID: "artscroisesDBmembreID"
  SA: "artscroisesServiceAccount"

cambristi:
  SCOPES:
    - 'https://www.googleapis.com/auth/gmail.readonly'
    - 'https://www.googleapis.com/auth/gmail.modify'
    - 'https://www.googleapis.com/auth/gmail.send'
  TOKEN_FILE: 'token.json'
  TOKEN_ID: "GmailToken"
  CREDENTIALS_ID: "GmailCredentials"
  WIX_API_TOKEN_ID: "cambristiApiToken"
  FOLDER: "news_to_send"
  MAIL: 'icambristi@gmail.com'
  SA: 'cambristiGoogleServiceAccount'
  max_addr_per_mail: 50
  max_mails_per_hour: 100
  pause: 1
  sendername: "I Cambristi ASBL"
  sender: 'icambristi@gmail.com'
  members: https://www.cambristi.com/_functions/members/
  SHEETID: 'cambristiMemberSheetID'