[project]
name = "sendmail"
version = "1.1.2"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "google-api-python-client>=2.187.0",
    "gspread>=6.2.1",
    "spamcheck>=1.0.4",
    "get-hc-secrets>=1.5.27",
    "oauth2client",
    "pillow>=12.2.0",
    "markdown2",
    "google-auth>=2.47.0",
    "google-auth-oauthlib>=1.2.2",
    "protobuf>=6.33.5",
    "pyasn1>=0.6.2"
]
