#!/bin/sh

FILE="data/20260420"
SUBJECT="Rappel I CAMBRISTI - avril 2026"

rm sendMail.log
python src/sendMail.py --md2html "$FILE.md"
scp -P 5210 "$FILE.html" contabo:/var/www/html/news/

rm sendMail.log
python src/sendMail.py -v  \
--profile cambristi \
-s "$SUBJECT" \
-cfg config.yml \
"$FILE.md"
