#
# Filtering options
# if all of the conditions are met, the subscriber is added to the mailing list
# - syntax:
#   filter:
#     <field_name>: <operation> <value>
#
#   where:
# <field_name>: is a field from the subscriber database (email, first_name...)
#   <operation>: is one of  "is", "is not", "gt", "lt", "ge", "le", "in", "not in"
#                           "is empty", "is not empty", "greater than", "less than"
#                           ,"greater or equal to", "less or equal to", "one of", "none of",
#                           "is equal to", "is not equal to"
#   <value>: is the value to compare with
#

artscroises:
  MAILCONFIG: 'artscroisesmailing'
  SHEETID: "artscroisesDBmembreID"
  SA: "artscroisesServiceAccount"
  domain: "artscroises.be"
  styles: "./css/styles.css"
  filter:
    email: is not empty
    status: is active
  filter_test:
    email: is not empty
    status: is active
    group: is Test
  default_message: |
    
    Chers amies et amis des Arts Croisés,
    ${body}
    Veuillez trouver en pièce jointe notre newsletter '${newsletter_name}'.
    Bonne lecture!
    
    L'équipe Arts Croisés, asbl.


cambristi:
  SCOPES:
    - 'https://www.googleapis.com/auth/gmail.readonly'
    - 'https://www.googleapis.com/auth/gmail.modify'
    - 'https://www.googleapis.com/auth/gmail.send'
  TOKEN_FILE: 'token.json'
  TOKEN_ID: "GmailToken"
  CREDENTIALS_ID: "GmailCredentials"
  WIX_API_TOKEN_ID: "cambristiApiToken"
  FOLDER: "news_to_send"
  MAIL: 'icambristi@gmail.com'
  SA: 'cambristiGoogleServiceAccount'
  max_addr_per_mail: 50
  max_mails_per_hour: 100
  pause: 1
  sendername: "I Cambristi ASBL"
  sender: "icambristi@gmail.com"   # "x@gmailapi.google.com"
  members: https://www.cambristi.com/_functions/members/
  SHEETID: 'cambristiMemberSheetID'
  filter:
    title: in member, participant, inactive
    email: is not empty
    emailBounced: is not True
  filter_test:
    title: in test, Test
    email: is not empty
  styles: "./css/styles.css"
  default_message: ''


cambristiEffective:
  SCOPES:
    - 'https://www.googleapis.com/auth/gmail.readonly'
    - 'https://www.googleapis.com/auth/gmail.modify'
    - 'https://www.googleapis.com/auth/gmail.send'
  TOKEN_FILE: 'token.json'
  TOKEN_ID: "GmailToken"
  CREDENTIALS_ID: "GmailCredentials"
  WIX_API_TOKEN_ID: "cambristiApiToken"
  FOLDER: "news_to_send"
  MAIL: 'icambristi@gmail.com'
  SA: 'cambristiGoogleServiceAccount'
  max_addr_per_mail: 50
  max_mails_per_hour: 100
  pause: 1
  sendername: "I Cambristi ASBL"
  sender: "icambristi@gmail.com"   # "x@gmailapi.google.com"
  members: https://www.cambristi.com/_functions/members/
  SHEETID: 'cambristiMemberSheetID'
  filter:
    membreEffectif: is True
    email: is not empty
    emailBounced: is not True
  filter_test:
    title: in test, Test
    email: is not empty
  styles: "./css/styles.css"
  default_message: ''

default:
  username: jdoe
  password: foobar
  sender: john.doe@example.com
  sendername: John Doe
  database: subscribers.csv
  smtp_host: smtp.example.com
  smtp_port: 587
  imap_host: imap.example.com
  imap_port: 993
  sent_folder: "Sent"
  default_message: ""
  pause: 1
  styles: "./css/styles.css"
  filter:
    email: is not empty
    bounced: is not bounced
    cotisation: greater than 0
    first_name: one of "Jean", "Xavier"
  filter_test:
    email: is "Toto the Tester"

