artscroises:
  default_documents_path: ''
  MAILCONFIG: artscroisesmailing
  SHEETID: artscroisesDBmembreID
  SA: artscroisesServiceAccount
  domain: artscroises.be
  styles: ./css/styles.css
  filter:
    email: is not empty
    status: is active
  filter_test:
    email: is not empty
    status: is active
    group: is Test
  default_message: "\nChers amies et amis des Arts Crois\xE9s,\n${body}\nVeuillez\
    \ trouver en pi\xE8ce jointe notre newsletter '${newsletter_name}'.\nBonne lecture!\n\
    \nL'\xE9quipe Arts Crois\xE9s, asbl.\n"
cambristi:
  default_documents_path: ''
  SCOPES:
  - https://www.googleapis.com/auth/gmail.readonly
  - https://www.googleapis.com/auth/gmail.modify
  - https://www.googleapis.com/auth/gmail.send
  TOKEN_FILE: token.json
  TOKEN_ID: GmailToken
  CREDENTIALS_ID: GmailCredentials
  WIX_API_TOKEN_ID: cambristiApiToken
  FOLDER: news_to_send
  MAIL: icambristi@gmail.com
  SA: cambristiGoogleServiceAccount
  max_addr_per_mail: 50
  max_mails_per_hour: 100
  pause: 1
  sendername: I Cambristi ASBL
  sender: icambristi@gmail.com
  members: https://www.cambristi.com/_functions/members/
  SHEETID: cambristiMemberSheetID
  filter:
    title: in member, participant, inactive
    email: is not empty
    emailBounced: is not True
  filter_test:
    title: in test, Test
    email: is not empty
  styles: ./css/styles.css
  default_message: ''
cambristiEffective:
  default_documents_path: ''
  SCOPES:
  - https://www.googleapis.com/auth/gmail.readonly
  - https://www.googleapis.com/auth/gmail.modify
  - https://www.googleapis.com/auth/gmail.send
  TOKEN_FILE: token.json
  TOKEN_ID: GmailToken
  CREDENTIALS_ID: GmailCredentials
  WIX_API_TOKEN_ID: cambristiApiToken
  FOLDER: news_to_send
  MAIL: icambristi@gmail.com
  SA: cambristiGoogleServiceAccount
  max_addr_per_mail: 50
  max_mails_per_hour: 100
  pause: 1
  sendername: I Cambristi ASBL
  sender: icambristi@gmail.com
  members: https://www.cambristi.com/_functions/members/
  SHEETID: cambristiMemberSheetID
  filter:
    membreEffectif: is True
    email: is not empty
    emailBounced: is not True
  filter_test:
    title: in test, Test
    email: is not empty
  styles: ./css/styles.css
  default_message: ''
#default:
#  default_documents_path: /Users/xavier/PycharmProjects/sendMail/data
#  username: jdoe
#  password: foobar
#  sender: john.doe@example.com
#  sendername: John Doe
#  database: Subscribers.csv
#  smtp_host: smtp.example.com
#  smtp_port: 587
#  imap_host: imap.example.com
#  imap_port: 993
#  sent_folder: Sent
#  default_message: ''
#  pause: 1
#  styles: ./css/styles.css
#  filter:
#    Email: is not empty
#    First Name: one of "Jean", "Xavier"
#  filter_test:
#    email: is "Toto the Tester"
