name: Build and Release Executables

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter the version (e.g., v1.0.0)"
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build executable
        run: pyinstaller --onefile  --noconfirm  --collect-submodules  './googleDriveLib.py' --add-data  './config.yml:.' sendMail.py

      - name: Rename executable
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv dist/sendMail.exe dist/sendMail-windows.exe
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            mv dist/sendMail dist/sendMail-linux
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            mv dist/sendMail dist/sendMail-macos
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sendMail-${{ matrix.os }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: List downloaded files (Debugging)
        run: ls -R

      - name: Make files executable (Linux/Mac)
        run: chmod +x sendMail-* || true

#      - name: Create GitHub Release
#        uses: softprops/action-gh-release@v2
#        with:
#          tag_name: ${{ github.event.inputs.version }}
#          name: Release ${{ github.event.inputs.version }}
#          draft: false
#          prerelease: false
#          files: |
#            sendMail-linux
#            sendMail-windows.exe
#            sendMail-macos
